#!/bin/bash

# Define the target configuration file location
CONFIG_FILE="/etc/nginx/snippets/cf-real-ip.conf"

# Retrieve the list of IPv4 and IPv6 addresses
IPS_V4=$(curl -s https://www.cloudflare.com/ips-v4)
IPS_V6=$(curl -s https://www.cloudflare.com/ips-v6)

# Start writing to the file
echo "" > $CONFIG_FILE # Clear the file
{
    echo "# Cloudflare real IP address ranges"
    echo "# Automatically generated by update-cf-real-ip.sh"
    echo ""

    # Write set_real_ip_from directive for IPv4 addresses
    for ip in $IPS_V4; do
        echo "set_real_ip_from $ip;"
    done

    # Write set_real_ip_from directive for IPv6 addresses
    for ip in $IPS_V6; do
        echo "set_real_ip_from $ip;"
    done

    # Set the real IP header, typically Cloudflare uses CF-Connecting-IP
    echo "real_ip_header CF-Connecting-IP;"
} >> $CONFIG_FILE

# Test Nginx configuration
nginx -t
if [ $? -eq 0 ]; then
    # If the Nginx configuration is ok, reload Nginx
    systemctl reload nginx
    echo "Cloudflare real IP configuration updated and nginx successfully reloaded."
else
    echo "Failed to reload nginx due to a configuration error."
fi
