#!/bin/bash

# Define the target configuration file location
CONFIG_FILE="/etc/nginx/snippets/cf-whitelist.conf"

# Retrieve the list of IPv4 and IPv6 addresses
IPS_V4=$(curl -s https://www.cloudflare.com/ips-v4)
IPS_V6=$(curl -s https://www.cloudflare.com/ips-v6)

# Start writing to the file
echo "" > $CONFIG_FILE
{
    echo "# Cloudflare IP ranges"
    echo "# Automatically generated by update-cf-ips.sh"
    echo ""

    # Write allow directive for IPv4 addresses
    for ip in $IPS_V4; do
        echo "allow $ip;"
    done

    # Write allow directive for IPv6 addresses
    for ip in $IPS_V6; do
        echo "allow $ip;"
    done

    # Other IP addresses not mentioned above are denied
    echo "deny all;"

} >> $CONFIG_FILE

# Test Nginx configuration
nginx -t
if [ $? -eq 0 ]; then
    # If the Nginx configuration is ok, reload Nginx
    systemctl reload nginx
    echo "Cloudflare IP whitelist updated and nginx successfully reloaded."
else
    echo "Failed to reload nginx due to a configuration error."
fi
